### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL 

### ISSUE THREAD

**Issue by semisight** [xdid-net/replace#1]
https://github.com/xdid-net/replace/blob/7d18b8aecafae191b98a16399703edafd1def747/template.tpl#L54

When reviewing your template we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [encodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by xdid-net** [comment]
Fixed with new version
